language: go
go:
  - "1.11"
install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.tar.gz -o hugo.tar.gz
  - tar -xvf hugo.tar.gz
script:
  - ./hugo --minify
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  target-branch: master
  fqdn: xuanwo.io
  on:
    branch: blog
