language: go
go:
  - "1.10"
install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.tar.gz -o hugo.tar.gz
  - tar -xvf hugo.tar.gz
script:
  - ./hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  target-branch: master
  fqdn: xuanwo.org
  on:
    branch: blog
