language: go
go:
  - "1.10"
before_install:
  - openssl aes-256-cbc -K $encrypted_e5256b70072f_key -iv $encrypted_e5256b70072f_iv -in .travis/travis.enc -out ~/.ssh/travis -d
  - eval `ssh-agent -s` && chmod 600 ~/.ssh/travis && ssh-add ~/.ssh/travis
install:
  - curl -L https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.tar.gz -o hugo.tar.gz
  - tar -xvf hugo.tar.gz
script:
  - ./hugo
after_success:
  - rsync -az --delete -e 'ssh -o StrictHostKeyChecking=no' public/ ${USER}@${HOST}:/srv/http
