auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Xuanwo.github.io
url: http://xuanwo.github.io
feed: /atom.xml
author_info: <a href="http://xuanwo.github.io/">Xuanwo</a>
