baseURL: "https://xuanwo.io"
languageCode: "en-US"
title: "Xuanwo's Blog"
pagination: 10

params:
  smartToc: true
  author: "Xuanwo"
  keywords:
    - "Technology"
    - "Code"
    - "Program"
    - "Linux"
  description: "Achieving Data Freedom Through Open Source and Rust"

menu:
  footer:
    - name: "about"
      url: "/about"
      weight: 1
    - name: "archives"
      url: "/archives/"
      weight: 2
    - name: "categories"
      url: "/categories/"
      weight: 3
    - name: "tags"
      url: "/tags/"
      weight: 4
    - name: "series"
      url: "/series/"
      weight: 5
    - name: "links"
      url: "/links/"
      weight: 6
    - name: "blogroll"
      url: "/blogroll/"
      weight: 7

  icon:
    - name: "rss"
      url: "/index.xml"
      weight: 1
    - name: "github"
      url: "https://github.com/Xuanwo"
      weight: 2
    - name: "send"
      url: "https://t.me/xuanwo_tweets"
      weight: 3
    - name: "twitter"
      url: "https://twitter.com/OnlyXuanwo"
      weight: 4
