<div id="start" class="container content">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <article class="clearfix">
                <div class="post-date">
                    May 26, 2014 | <a href="">Melissa Sing </a> <span><a href="">11 Comments</a></span>
                </div>
                <h2><a href="post-typography.html">We don't have a brig</a></h2>
                <p>Use this resource to highlight the points of interest of your products. Just a click to open a brief
                    description of each point, allowing your user to get a deep and fast understanding of your product
                    features. <a class="" href="post-typography.html">Read more</a>
                </p>
            </article>
            <article class="clearfix">
                <div class="post-date">
                    May 26, 2014 | <a href="">Melissa Sing </a> <span><a href="">42 Comments</a></span>
                </div>
                <h2><a href="post-image.html">Every other day it's food, food, food.</a></h2>
                <p>I suppose I could part with 'one' and still be feared… I don't 'need' to drink. I can quit anytime I
                    want! Oh, I think we should just stay friends. Noooooo! Five hours? Aw, man! Couldn't you just get
                    me the death penalty? <a class="" href="post-image.html">Read more</a>
                </p>
            </article>
            <article class="clearfix">
                <div class="post-date">
                    May 12, 2014 | <a href="">Melissa Sing </a> <span><a href="">2 Comments</a></span>
                </div>
                <h2><a href="post-audio.html">Ah, now the ball's in Farnsworth's court!</a></h2>
                <p>Bender, hurry! This fuel's expensive! Also, we're dying! Fry, we have a crate to deliver. In your
                    time, yes, but nowadays shut up! Besides, these are adult stemcells, harvested from perfectly
                    healthy adults whom I killed for their stemcells. This is the worst part. The calm before the
                    battle. <a class="" href="post-audio.html">Read more</a>
                </p>
            </article>
            <article class="clearfix last">
                <div class="post-date">
                    May 10, 2014 | <a href="">Melissa Sing </a> <span><a href="">23 Comments</a></span>
                </div>
                <h2><a href="post-video.html">But I've never been to the moon!</a></h2>
                <p>But I've never been to the moon! I found what I need. And it's not friends, it's things. Can I use
                    the gun? Incidentally, you have a dime up your nose. One hundred dollars. <a class=""
                                                                                                 href="post-video.html">Read
                        more</a>
                </p>
            </article>

            <div class="post-popular">
                <div class="row hidden-xs">
                    <div class="col-sm-4 col-md-4">
                        <a href="post-video.html"><img src="img/img2.jpg" class="img-responsive" alt="img2"></a>
                        <h4 class="text-center"><a href="post-video.html">But I've never been to the moon!</a></h4>
                        <p class="post-date text-center">MAY 10, 2014</p>
                    </div>
                    <div class="col-sm-4 col-md-4">
                        <a href="post-typography.html"><img src="img/img1.jpg" class="img-responsive" alt="img1"></a>
                        <h4 class="text-center"><a href="post-typography.html">We don't have a brig</a></h4>
                        <p class="post-date text-center">september 27, 2014</p>

                    </div>
                    <div class="col-sm-4 col-md-4">
                        <a href="post-image.html"><img src="img/img3.jpg" class="img-responsive" alt="img3"></a>
                        <h4 class="text-center"><a href="post-image.html">Every other day it's food, food, food.</a>
                        </h4>
                        <p class="post-date text-center">april 2, 2014</p>

                    </div>
                </div>
                <div class="row visible-xs">
                    <div class="col-sm-12">
                        <div class="media">
                            <a class="pull-left" href="post-video.html"><img class="media-object" src="img/img2.jpg"
                                                                             width="100" alt=""></a>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="post-video.html">But I've never been to the moon!</a>
                                </h4>
                                <p class="post-date">may 10, 2014</p>
                            </div>
                        </div>
                        <div class="media">
                            <a class="pull-left" href="post-typography.html"><img class="media-object"
                                                                                  src="img/img1.jpg" width="100" alt=""></a>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="post-typography.html">We don't have a brig</a></h4>
                                <p class="post-date">september 27, 2014</p>
                            </div>
                        </div>
                        <div class="media">
                            <a class="pull-left" href="post-image.html"><img class="media-object" src="img/img3.jpg"
                                                                             width="100" alt=""></a>
                            <div class="media-body">
                                <h4 class="media-heading"><a href="post-image.html">Every other day it's food, food,
                                        food.</a></h4>
                                <p class="post-date">april 2, 2014</p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="paging clearfix">
                <a class="btn pull-left" href="#"><i class="icon-arrow-left2 left"></i><span>Older</span><span
                            class="hidden-xs"> Posts</span></a>
                <a class="btn pull-right" href="#"><span>Newer</span><span class="hidden-xs"> Posts</span><i
                            class="icon-arrow-right2 right"></i></a>
            </div>

        </div>
    </div><!-- end row -->
</div>