name = "Harbor"
license = "MIT"
description = "A theme for https://xuanwo.io"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.20

[author]
  name = "Xuanwo"
  homepage = "https://xuanwo.io"
