name = "Harbor"
license = "MIT"
description = "A theme for https://xuanwo.io/, idea borrowed from https://www.taniarascia.com/"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.54

[author]
  name = "Xuanwo"
  homepage = "https://xuanwo.io"
