name: Deploy to GitHub Pages

on:
  push:
    branches:
      - blog

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: gh-pages
      uses: ./.github/actions/hugo
      env:
        GIT_BRANCH: master
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
